// Generates tiny base64 LQIP placeholders for every artwork and detail crop.
// Run: node scripts/generate-blur.mjs
import sharp from "sharp";
import fs from "node:fs";
import path from "node:path";

const dir = path.join(process.cwd(), "public", "artworks");
const out = path.join(process.cwd(), "src", "content", "blur.ts");

const entries = {};
const files = fs.readdirSync(dir).filter((f) => f.endsWith(".jpg"));
for (const f of files.sort()) {
  const buf = await sharp(path.join(dir, f))
    .resize(16, 16, { fit: "inside" })
    .jpeg({ quality: 40 })
    .toBuffer();
  entries[`/artworks/${f}`] = `data:image/jpeg;base64,${buf.toString("base64")}`;
}

const body = Object.entries(entries)
  .map(([k, v]) => `  "${k}":\n    "${v}",`)
  .join("\n");

fs.writeFileSync(
  out,
  `// GENERATED by scripts/generate-blur.mjs — do not edit by hand.\n` +
    `// Tiny base64 placeholders so images fade in without layout shift (§25).\n\n` +
    `export const BLUR: Record<string, string> = {\n${body}\n};\n`
);
console.log(`wrote ${Object.keys(entries).length} placeholders to src/content/blur.ts`);
